name: Limitime
version: 1.7.10-0.4.1
author: Himmelt
main: org.soraworld.lime.Limitime
website: https://github.com/Himmelt/Limitime
description: Limit time using for items.

commands:
  lime:
    description: "Limitime - https://github.com/Himmelt/Limitime"
    usage: "[Limitime] /lime save|reload|lang|..."
    permission: lime.admin
    permission-message: "[Limitime] You have no permission <lime.admin>"
permissions:
  lime.admin:
    default: op
