name: Limitime
version: ${version}
author: Himmelt
main: org.soraworld.limitime.Limitime
website: https://github.com/Himmelt/Limitime
description: Limit time using for items.
commands:
  limitime:
    aliases: [limit]
    description: "Limitime - https://github.com/Himmelt/Limitime"
    usage: "/limit append|add|plus"
    permission: limitime.admin
    permission-message: "You have no permission <limitime.admin>"
permissions:
  limitime.admin:
    default: op
