name: Limitime
version: 1.7.10-0.4.3
author: Himmelt
main: org.soraworld.lime.Limitime
depend: [Violet]
softdepend: []
website: https://github.com/Himmelt/Limitime
description: Limit time using for items.
commands:
  limitime:
    aliases: [lime,limit]
    description: "Limitime - https://github.com/Himmelt/Limitime"
    usage: "/lime append|add|app"
    permission: limit.admin
    permission-message: "You have no permission <limit.admin>"
permissions:
  limitime.admin:
    default: op
