name: Limitime
version: 1.7.10-0.4.2
author: Himmelt
main: org.soraworld.lime.Limitime
website: https://github.com/Himmelt/Limitime
description: Limit time using for items.

commands:
  limit:
    description: "Limitime - https://github.com/Himmelt/Limitime"
    usage: "[Limitime] /lime save|reload|lang|death|append|add|app"
    permission: limit.admin
    permission-message: "[Limitime] You have no permission <limit.admin>"
permissions:
  limit.admin:
    default: op
