name: Limitime
version: 1.7.10-0.3.0
author: Himmelt
main: org.soraworld.limitime.Limitime
website: https://github.com/SoraWorld/Limitime
description: Limit time using for items.

commands:
  limitime:
    description: 物品限时使用
    usage: /limitime
